const countriesAbbreviation = {
    "France":"FR",
    "Germany":"DE",
    "Poland":"PL",
    "Albania":"AL",
    "Russia":"RU",
    "Greece":"GR",
    "Portugal":"PT",
    "Belgium":"BE",
    "Iceland":"IS",
    "Romania":"RO",
    "Bulgaria":"BG",
    "Ireland":"IE",
    "Croatia":"HR",
    "Italy":"IT",
    "Spain":"ES",
    "Cyprus":"CY",
    "Latvia":"LV",
    "Sweden":"SE",
    "Denmark":"DK",
    "Lithuania":"LT",
    "Ukraine":"UA",
    "Estonia":"EE",
    "Malta":"MT",
    "United Kingdom":"GB",
    "Faroe Islands":"FO",
    "Netherlands":"NL",
    "Finland":"FI",
    "Norway":"NO",
    "Anguilla":"AI",
    "El Salvador":"SV",
    "Nicaragua":"NI",
    "Aruba":"AW",
    "Grenada":"GD",
    "Panama":"PA",
    "Bahamas":"BS",
    "Guadeloupe":"GP",
    "Puerto Rico":"PR",
    "Barbados":"BB",
    "Guatemala":"GT",
    "Saint Barthélemy":"BL",
    "Belize":"BZ",
    "Haiti":"HT",
    "Saint Kitts and Nevis":"KN",
    "Bermuda":"BM",
    "Honduras":"HN",
    "Saint Lucia":"LC",
    "British Virgin Islands":"VG",
    "Jamaica":"JM",
    "Trinidad and Tobago":"TT",
    "Canada":"CA",
    "Martinique":"MQ",
    "Turks and Caicos Islands":"TC",
    "Cayman Islands":"KY",
    "Mexico":"MX",
    "Costa Rica":"CR",
    "Montserrat":"MS",
    "Dominican Republic":"DO",
    "USA":"US",
    "Micronesia":"FM",
    "Fikland Islands":"FK",
    "Reunion":"RE",
    "Turkey":"TR",
    "American Samoa":"AS",
    "Kiribati":"KI",
    "Papua New Guinea":"PG",
    "Cook Islands":"CK",
    "Samoa":"WS",
    "New Caledonia":"NC",
    "Solomon Islands":"SB",
    "Fiji":"FJ",
    "New Zealand":"NZ",
    "Tokelau":"TK",
    "French Polynesia":"PF",
    "Northern Mariana Islands":"MP",
    "Tonga":"TO",
    "Guam":"GU",
    "Palau":"PW",
    "Vanuatu":"VU",
    "Australia":"AU",
    "Argentina":"AR",
    "Ecuador":"EC",
    "Uruguay":"UY",
    "Brazil":"BR",
    "Venezuela":"VE",
    "Chile":"CL",
    "French Guiana":"GF",
    "Colombia":"CO",
    "Peru":"PE",
    "Algeria":"DZ",
    "Liberia":"LR",
    "Senegal":"SN",
    "Angola":"AO",
    "Libya":"LY",
    "Seychelles":"SC",
    "Benin":"BJ",
    "Madagascar":"MG",
    "Sierra Leone":"SL",
    "Cameroon":"CM",
    "Mauritania":"MR",
    "Somalia":"SO",
    "Mauritius":"MU",
    "South Africa":"ZA",
    "Côte d'Ivoire":"CI",
    "Morocco":"MA",
    "Egypt":"EG",
    "Mozambique":"MZ",
    "Tanzania":"TZ",
    "Gabon":"GA",
    "Namibia":"NA",
    "Togo":"TG",
    "Gambia":"GM",
    "Nigeria":"NG",
    "Tunisia":"TN",
    "Ghana":"GH",
    "Republic of the Congo":"CG",
    "Western Sahara":"EH",
    "Kenya":"KE",
    "Bangladesh":"BD",
    "Kazakhstan":"KZ",
    "Sri Lanka":"LK",
    "Brunei Darussalam":"BN",
    "Kuwait":"KW",
    "Taiwan":"TW",
    "Cambodia":"KH",
    "Lebanon":"LB",
    "Thailand":"TH",
    "China":"CN",
    "Malaysia":"MY",
    "Christmas Island":"CX",
    "Maldives":"MV",
    "United Arab Emirates":"AE",
    "India":"IN",
    "Oman":"OM",
    "Vietnam":"VN",
    "Indonesia":"ID",
    "Pakistan":"PK",
    "Yemen":"YE",
    "Israel":"IL",
    "Philippines":"PH",
    "Japan":"JP",
    "South Korea":"KR"
}