[application]
public_url = "/"

[web.app]

# HTML title tag content
title = "wAIves"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = [
    "/src/style.css"
]

# Additional JavaScript files
script = [
    "https://cdn.jsdelivr.net/npm/@tensorflow/tfjs",
    "assets/tensorflow.js",
]

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
