[application]
public_url = "/"

[web.app]
title = "wAIves"
favicon = "assets/favicon.ico"

[web.resource]
style = [
    "assets/style.css"
]

script = [
    "https://cdn.jsdelivr.net/npm/@tensorflow/tfjs",
    "assets/tensorflow.js",
]

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
