name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: rust-src, rustfmt, clippy

      - name: Install dx tool
        run: cargo install dx

      - name: Build application
        run: |
          cd app
          dx bundle --out-dir docs

      - name: Prepare GitHub Pages files
        run: |
          # Create the 'docs' folder
          mkdir -p docs
          
          # Move the created files
          mv app/docs/public/* docs/
          
          # Create the 404.html file
          cp docs/index.html docs/404.html
          
          # Copy the resources
          cp app/src/tensorflow.js docs/
          cp app/src/style.css docs/
          cp app/assets/favicon.ico docs/

          # Find the WASM/JS files
          wasm_file=$(find docs/assets -name '*.wasm' | head -n1)
          js_file=$(find docs/assets -name '*.js' | head -n1)
          
          if [ -z "$wasm_file" ] || [ -z "$js_file" ]; then
            echo "::error::Fichiers WASM ou JS introuvables"
            exit 1
          fi
          
          wasm_name=$(basename "$wasm_file")
          js_name=$(basename "$js_file")
          
          echo "WASM file: $wasm_name"
          echo "JS file: $js_name"
          
          # Update the references in index.html
          sed -i -E \
            -e "s/\/assets\/[^\"]+\.wasm/\/assets\/$wasm_name/g" \
            -e "s/\/assets\/[^\"]+\.js/\/assets\/$js_name/g" \
            docs/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GHT }}
          publish_dir: ./docs