name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: rust-src, rustfmt, clippy

      - name: Install dx tool
        run: cargo install dx

      - name: Build application
        run: |
          cd app
          # Ajout du base-path pour corriger les chemins relatifs
          dx bundle --out-dir ../docs --base-path /

      - name: Prepare GitHub Pages files
        run: |
          # Créer le dossier assets pour les ressources
          mkdir -p docs/assets
          
          # Déplacer les fichiers WASM/JS dans assets
          find docs -name '*.wasm' -exec mv {} docs/assets/ \;
          find docs -name '*.js' ! -name 'index.js' -exec mv {} docs/assets/ \;
          
          # Copier les ressources spécifiques
          cp app/src/tensorflow.js docs/assets/
          cp app/src/style.css docs/assets/
          cp app/assets/favicon.ico docs/assets/
          
          # Mettre à jour les références dans index.html
          sed -i -E \
            -e 's/"\/(.*\.wasm)"/"\/assets\/\1"/g' \
            -e 's/"\/(.*\.js)"/"\/assets\/\1"/g' \
            -e 's/"\/(tensorflow\.js)"/"\/assets\/\1"/g' \
            -e 's/"\/(style\.css)"/"\/assets\/\1"/g' \
            -e 's/"\/(favicon\.ico)"/"\/assets\/\1"/g' \
            docs/index.html

          # Créer la page 404.html
          cp docs/index.html docs/404.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs